linters-settings:
  goimports:
    local-prefixes: github.com/chronosphereio/calyptia-core-fluent-bit-dummy
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 15
  govet:
    check-shadowing: true
  misspell:
    locale: US
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: true # require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  funlen:
    lines: 1000
    statements: 250

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - typecheck
    - bodyclose
    # - depguard
    - dupl
    - exportloopref
    - forcetypeassert
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofumpt
    - revive
    - gomnd
    - goprintffuncname
    - gosec
    - misspell
    - noctx
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - whitespace
    - funlen
issues:
  exclude-use-default: false
  exclude:
    - 'declaration of "(err|ctx)" shadows declaration at'
  exclude-rules:
    - linters:
        - gomnd
      text: "mnd: Magic number: 10"
    - linters:
        - gomnd
      text: "mnd: Magic number: 64"
