# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json

version: 2

builds:
  - id: linux-amd64
    builder: prebuilt
    goos:
      - linux
    goarch:
      - amd64
    goamd64: ["v1"]
    prebuilt:
      path: ./build/{{ .Arch }}/calyptia-core-fluent-bit-dummy.so
    binary: lib-calyptia-core-fluent-bit-dummy.so

  - id: linux-arm64
    builder: prebuilt
    goos:
      - linux
    goarch:
      - arm64
    prebuilt:
      path: ./build/{{ .Arch }}/calyptia-core-fluent-bit-dummy.so
    binary: lib-calyptia-core-fluent-bit-dummy.so

archives:
  - id: linux
    allow_different_binary_count: true
    builds:
      - linux-amd64
      - linux-arm64
    files:
      - LICENSE.txt
      - README.md
sboms:
  - artifacts: archive
signs:
  - artifacts: checksum
    args:
      [
        "--batch",
        "-u",
        "{{ .Env.GPG_FINGERPRINT }}",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}",
      ]
