name: Lint PRs
on:
  pull_request:
  workflow_dispatch:

jobs:

  hadolint-pr:
    runs-on: ubuntu-latest
    name: PR - Hadolint
    steps:
      - uses: actions/checkout@v4
        # Ignores do not work: https://github.com/reviewdog/action-hadolint/issues/35 is resolved
      - uses: reviewdog/action-hadolint@v1

  shellcheck-pr:
    runs-on: ubuntu-latest
    name: PR - Shellcheck
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@master

  actionlint-pr:
    runs-on: ubuntu-latest
    name: PR - Actionlint
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color -shellcheck=
        shell: bash

  docslint-pr:
      runs-on: ubuntu-latest
      name: PR - Markdownlint
      steps:
        - name: Run markdownlint
          uses: actionshub/markdownlint@v3.1.4

  golint-pr:
    runs-on: ubuntu-latest
    name: PR - GO lint
    steps:
      - uses: actions/checkout@v4

      - name: Install cmetrics library
        run: |
          curl -L https://github.com/fluent/cmetrics/releases/download/${CMETRICS_RELEASE}/cmetrics_${CMETRICS_VERSION}_${ARCH}-headers.deb  --output cmetrics_${CMETRICS_VERSION}_${ARCH}-headers.deb
          curl -L https://github.com/fluent/cmetrics/releases/download/${CMETRICS_RELEASE}/cmetrics_${CMETRICS_VERSION}_${ARCH}.deb --output cmetrics_${CMETRICS_VERSION}_${ARCH}.deb
          sudo dpkg -i *.deb
        env:
          CMETRICS_VERSION: "0.5.8"
          CMETRICS_RELEASE: "v0.5.8"
          ARCH: "amd64"

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2